---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: bobtest-kubeapplier
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: Namespace
apiVersion: v1
metadata:
  name: bob-test-kubeapplier
  labels:
    name: bob-test-kubeapplier
